### ISSUE TITLE
Problem 3.2

### ISSUE THREAD

**Issue by Aspirisha** [GoldenCheese/PRML-Solution-Manual#16]
It seems that the proof of non-singularity is invalid. In fact, matrix &Phi;<sup>T</sup>&Phi; **can** be singular

 quote from the 3.1.2

> In practice, a direct solution of the normal equations can lead to numerical difficulties when &Phi;<sup>T</sup>&Phi;  is close to singular

Your proof of non-singularity is no-good since you suppose that &phi;<sub>1</sub>...&phi;<sub>M</sub> together are the basis of subspace which is spanned by &Phi;'s columns. However, there is no reason to suppose this: they all can be collinear for instance, then any one of them will represent the basis of the subspace. 

There is no need to proof that &Phi;<sup>T</sup>&Phi; is invertible anyway since its inverse is the part of the matrix which is given as an existing object in the task condition; (this implies (&Phi;<sup>T</sup>&Phi;)<sup>-1</sup> exists).

**Comment by zhengqigao** [comment]
Thanks. You are right. As I was writing the solution for this problem, I was not aware of the matrix rank. 
Of course, \Phi^T\Phi might not be invertible. For instance,  when N<M, since we know rank(\Phi^T\Phi)= rank(\Phi) <= N and \Phi^T\Phi has size of M*M, we know \Phi^T\Phi doesn't have full rank, which means it is not invertible.

I have updated the solution manual. Thanks again.
